import asyncio
import json
import os
import smtplib
from datetime import datetime
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from playwright.async_api import async_playwright

# Read from environment variables (set as GitHub Secrets)
SENDER_EMAIL    = os.environ["SENDER_EMAIL"]
SENDER_PASSWORD = os.environ["SENDER_PASSWORD"]
RECIPIENT_EMAIL = os.environ["RECIPIENT_EMAIL"]

BMS_URL       = "https://in.bookmyshow.com/explore/events-mumbai?categories=music-shows"
SNAPSHOT_FILE = "known_events.json"


async def scrape_events() -> list[dict]:
    events = []
    async with async_playwright() as p:
        browser = await p.chromium.launch(
            headless=True,
            args=["--no-sandbox", "--disable-setuid-sandbox"]
        )
        context = await browser.new_context(
            user_agent=(
                "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                "AppleWebKit/537.36 (KHTML, like Gecko) "
                "Chrome/120.0.0.0 Safari/537.36"
            ),
            viewport={"width": 1280, "height": 900},
        )
        page = await context.new_page()
        print("🌐 Navigating to BookMyShow...")
        await page.goto(BMS_URL, wait_until="domcontentloaded", timeout=60000)
        await page.wait_for_selector('a[href*="/events/"]', timeout=30000)

        for _ in range(6):
            await page.evaluate("window.scrollBy(0, window.innerHeight)")
            await page.wait_for_timeout(1200)

        card_els = await page.query_selector_all('a[href*="/events/"]')
        print(f"🃏 Found {len(card_els)} card elements")

        seen_titles = set()
        for card in card_els:
            try:
                inner_text = await card.inner_text()
                lines = [l.strip() for l in inner_text.strip().split('\n') if l.strip()]
                if not lines:
                    continue
                title = lines[0]
                if not title or title in seen_titles:
                    continue
                seen_titles.add(title)
                venue = lines[1] if len(lines) > 1 else "Venue TBA"
                price = lines[3] if len(lines) > 3 else (lines[-1] if len(lines) > 1 else "")
                href  = await card.get_attribute("href") or ""
                url   = href if href.startswith("http") else f"https://in.bookmyshow.com{href}"
                events.append({"title": title, "venue": venue, "price": price, "url": url})
            except Exception:
                continue

        await browser.close()
    print(f"✅ Scraped {len(events)} unique events")
    return events


def load_known_events() -> set[str]:
    if os.path.exists(SNAPSHOT_FILE):
        with open(SNAPSHOT_FILE) as f:
            return set(json.load(f))
    return set()


def save_known_events(titles: set[str]) -> None:
    with open(SNAPSHOT_FILE, "w") as f:
        json.dump(list(titles), f, indent=2)


def send_email(new_events: list[dict]) -> None:
    rows = ""
    for ev in new_events:
        rows += f"""
        <tr>
          <td style="padding:10px 12px;border-bottom:1px solid #eee;">
            <a href="{ev['url']}" style="font-weight:600;color:#e2163b;text-decoration:none;">{ev['title']}</a>
          </td>
          <td style="padding:10px 12px;border-bottom:1px solid #eee;color:#555;">{ev['venue']}</td>
          <td style="padding:10px 12px;border-bottom:1px solid #eee;color:#27ae60;">{ev.get('price','')}</td>
        </tr>"""

    html = f"""
    <html><body style="font-family:Arial,sans-serif;max-width:700px;margin:auto;">
      <h2 style="color:#e2163b;">🎵 New Music Events on BookMyShow – Mumbai</h2>
      <p>Found <strong>{len(new_events)}</strong> new event(s) as of {datetime.now().strftime('%d %b %Y, %I:%M %p')} UTC:</p>
      <table width="100%" style="border-collapse:collapse;font-size:14px;">
        <thead>
          <tr style="background:#f5f5f5;">
            <th style="padding:10px 12px;text-align:left;">Event</th>
            <th style="padding:10px 12px;text-align:left;">Venue</th>
            <th style="padding:10px 12px;text-align:left;">Price</th>
          </tr>
        </thead>
        <tbody>{rows}</tbody>
      </table>
      <p style="margin-top:20px;font-size:12px;color:#999;">Auto-generated by your BookMyShow scraper 🤖</p>
    </body></html>
    """

    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"🎵 {len(new_events)} New Music Event(s) on BookMyShow Mumbai!"
    msg["From"]    = SENDER_EMAIL
    msg["To"]      = RECIPIENT_EMAIL
    msg.attach(MIMEText(html, "html"))

    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
        server.login(SENDER_EMAIL, SENDER_PASSWORD)
        server.sendmail(SENDER_EMAIL, RECIPIENT_EMAIL, msg.as_string())
    print(f"📧 Email sent → {RECIPIENT_EMAIL}")


async def main():
    known   = load_known_events()
    scraped = await scrape_events()

    if not scraped:
        print("⚠️ No events scraped.")
        return

    new_events = [ev for ev in scraped if ev["title"] not in known]

    if new_events:
        print(f"🆕 {len(new_events)} new event(s) found!")
        send_email(new_events)
    else:
        print("✅ No new events since last check.")

    save_known_events(known | {ev["title"] for ev in scraped})
    print(f"💾 Snapshot updated")


asyncio.run(main())
